Dinner/Controllers/MenuController.cs
using System;
using System.Web.Mvc;

using Dinner.Entities;
using Dinner.Models;

namespace Dinner.Controllers
{
    using System.Collections.Generic;

    using Dinner.Services;

    [Authorize]
    public class MenuController : BaseController
    {
        private const int CompanyID = 1;

        private readonly IMenuService menuService;

        private readonly IOrderService orderService;

        private readonly ICompanyService companyService;

        public MenuController(
            IMenuService menuService, 
            IOrderService orderService, 
            ICalendarService calendarService,
            ICompanyService companyService) : base(calendarService)
        {
            this.menuService = menuService;
            this.orderService = orderService;
            this.companyService = companyService;
        }

        [AllowAnonymous]
        public ActionResult Index(string date)
        {
            if (User.Identity.IsAuthenticated)
            {
                return this.OrderMenu(date);
            }

            return ViewMenu(date);
        }

        [AllowAnonymous]
        public ActionResult ViewMenu(string date)
        {
            var menuDate = this.GetMenuDate(date);

            var menuCourses = this.menuService.GetDayMenu(menuDate);
            var companySettings = this.companyService.GetSettings(CompanyID);

            var viewModel = new MenuModel
                {
                    Date = menuDate,
                    MenuCourses = menuCourses,
                    CompanySettings = companySettings
                };
            return View("ViewMenu", viewModel);
        }

        public ActionResult OrderMenu(string date)
        {
            var menuDate = this.GetMenuDate(date);
            if (string.IsNullOrEmpty(date))
                return this.RedirectToAction("Index", new { date = menuDate.ToString("yyyy-MM-dd") });

            var isFreezed = this.orderService.IsMenuFreezedForDate(menuDate);
            var model = new OrderModel
            {
                Date = menuDate,
                IsFreezed = isFreezed
            };

            return View("OrderMenu", model);
        }

        public ActionResult UserOrders()
        {
            var startDate = this.CalendarService.GetCurrentDate().Date;
            var endDate = startDate.AddDays(8);

            var orders = this.orderService.GetUserOrders(startDate, startDate.AddMonths(1));
            var frozedDates = new HashSet<DateTime>();

            for (var orderDate = startDate; orderDate < endDate; orderDate = orderDate.AddDays(1))
            {
                if (!orders.ContainsKey(orderDate.Date) && this.CalendarService.IsWorkingDay(orderDate))
                {
                    orders[orderDate.Date] = new UserOrdersModel {Orders = new List<OrderedMenuModel>()};
                }

                if (this.orderService.IsMenuFreezedForDate(orderDate))
                {
                    frozedDates.Add(orderDate.Date);
                }
            }

            ViewBag.NextWorkingDate = startDate;
            ViewBag.FrozenDates = frozedDates;
            ViewBag.DeleteFrozenDate = GetDeleteFrozenDate();

            return this.View("UserOrders", orders);
        }

        public ActionResult ngUserOrders()
        {
            return this.View();
        }

        private DateTime GetDeleteFrozenDate()
        {
            DateTime now = this.CalendarService.GetCurrentDate();
            return this.CalendarService.GetDateWithNewTime(now, 11, 30);
        }
    }
}

Dinner/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;

using Dinner.Attributes;
using Dinner.Entities;
using Dinner.Models;
using Dinner.Models.Orders;

namespace Dinner.Controllers
{
    using System.Linq;

    using Dinner.Services;
    using Dinner.Services.Security;

    [Authorize]
    [Admin]
    public class OrdersController : BaseController
    {
        private readonly IOrderService orderService;

        private readonly IDinnerPrincipalProvider principalProvider;

        public OrdersController(IOrderService orderService, IDinnerPrincipalProvider principalProvider, ICalendarService calendarService) : base(calendarService)
        {
            this.orderService = orderService;
            this.principalProvider = principalProvider;
        }

        public ActionResult Index(string date)
        {
            var viewModel = this.GetOrdersForDate(date);

            return View(viewModel);
        }

        public ActionResult Sales()
        {
            return this.View();
        }


        public ActionResult Print(string date)
        {
            OrdersModel viewModel = this.GetOrdersForDate(date);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult RemoveOrder(int orderId, DateTime date)
        {
            this.orderService.RemoveOrder(orderId, date);

            return this.RedirectToAction("Index", new { date = date.ToString("yyyy-MM-dd") });
        }

        private OrdersModel GetOrdersForDate(string date)
        {
            var menuDate = this.GetMenuDate(date);

            var usersOrders = this.orderService.GetAllOrdersForDay(this.principalProvider.Principal.CompanyID, menuDate).ToList();
            var orders = this.GetOrders(usersOrders);

            var viewModel = new OrdersModel
                {
                    Date = menuDate,
                    UsersOrders = usersOrders,
                    Orders = orders
                };

            return viewModel;
        }

        private IEnumerable<OrderedMenuModel> GetOrders(IEnumerable<UserOrdersModel> usersOrders)
        {
            var orders = new Dictionary<int, OrderedMenuModel>();

            foreach (var userOrders in usersOrders)
            {
                foreach (var order in userOrders.Orders)
                {
                    if (!orders.ContainsKey(order.Course.ID))
                    {
                        orders[order.Course.ID] = new OrderedMenuModel { Course = order.Course, Quantity = 0, IsPurchased = order.IsPurchased};
                    }

                    orders[order.Course.ID].Quantity += order.Quantity;
                }
            }

            return orders.Values;
        }

        private IList<ReportOrderedItemModel> GetOrdersWithPurchased(IEnumerable<UserOrdersModel> usersOrders)
        {
            var orders = new Dictionary<int, ReportOrderedItemModel>();
            foreach (var userOrders in usersOrders)
            {
                foreach (var order in userOrders.Orders)
                {
                        if (!orders.ContainsKey(order.Course.ID))
                        {
                            orders[order.Course.ID] = new ReportOrderedItemModel
                            {
                                Course = order.Course
                            };
                        }

                    if (order.IsPurchased)
                    {
                        orders[order.Course.ID].PurchasedQuantity += order.Quantity;
                    }
                    else
                    {
                        orders[order.Course.ID].ResidueQuantity += order.Quantity;
                    }
                }
            }

            return orders.Values.ToList();
        }
    }
}

Dinner/Controllers/WebCamController.cs
using System.Web.Mvc;

namespace Dinner.Controllers
{
    public class WebCamController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Dinner/Views/Shared/_Layout.cshtml
@using Dinner
@using Dinner.Helpers
<!DOCTYPE html>
<html lang="en" xmlns:ng="http://angularjs.org" xmlns:lt="http://lunch-time.co">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @RenderSection("header", required: false)
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css/dinner")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryform")
    @Scripts.Render("~/bundles/toastr")
</head>
<body>
    <header id="topMenuContainer" class="navbar navbar-default navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Content("~/")" target="_self">
                    <img src="@Url.Content("~/Images/logo.gif")" alt="Intermedia Dinners" title="Intermedia Dinners">
                    Lunch Time
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        @Html.MenuActionLink("Заказ обедов", "Index", "Menu")
                    }
                    else
                    {
                        // TODO - currently user cannot get here
                        @Html.MenuActionLink("Просмотр меню", "Index", "Menu")
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.MenuActionLink("Формирование меню", "Index", "Admin")

                        @Html.MenuActionLink("Заказы", "Index", "Orders")
                    }
                    @if (User.IsInRole("User"))
                    {
                        @Html.MenuActionLink("Статистика", "Index", "Statistics")
                    }
                    @Html.MenuActionLink("Камера", "Index", "WebCam")
                    @Html.MenuActionLink("Что нового?", "Index", "Version")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </header>
    <div class="full-height">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        // Include the UserVoice JavaScript SDK (only needed once on a page)
        UserVoice = window.UserVoice || []; (function () { var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true; uv.src = '//widget.uservoice.com/CmqROajwF9kdTNj53taa7w.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s) })();

        //
        // UserVoice Javascript SDK developer documentation:
        // https://www.uservoice.com/o/javascript-sdk
        //

        // Set colors
        UserVoice.push(['set', {
            accent_color: '#e23a39',
            trigger_color: 'white',
            trigger_background_color: '#e23a39'
        }]);

        // Identify the user and pass traits
        // To enable, replace sample data with actual user traits and uncomment the line
        UserVoice.push(['identify', {
            //email:      'john.doe@example.com', // User’s email address
            //name:       'John Doe', // User’s real name
            //created_at: 1364406966, // Unix timestamp for the date the user signed up
            //id:         123, // Optional: Unique id of the user (if set, this should not change)
            //type:       'Owner', // Optional: segment your users by type
            //account: {
            //  id:           123, // Optional: associate multiple users with a single account
            //  name:         'Acme, Co.', // Account name
            //  created_at:   1364406966, // Unix timestamp for the date the account was created
            //  monthly_rate: 9.99, // Decimal; monthly rate of the account
            //  ltv:          1495.00, // Decimal; lifetime value of the account
            //  plan:         'Enhanced' // Plan name for the account
            //}
        }]);

        // Add default trigger to the bottom-right corner of the window:
        UserVoice.push(['addTrigger', { mode: 'smartvote', trigger_position: 'bottom-right' }]);

        // Or, use your own custom trigger:
        //UserVoice.push(['addTrigger', '#id', { mode: 'smartvote' }]);

        // Autoprompt for Satisfaction and SmartVote (only displayed under certain conditions)
        UserVoice.push(['autoprompt', {}]);
    </script>
</body>
</html>

Dinner/Views/Shared/_LayoutWithMenu.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header
{
    @RenderSection("header", required: false)
}

<div class="content">
    <div class="sidebar-nav">
        @SideBar.Render(ViewBag.Date, ViewBag.NextWorkingDate)
        @RenderSection("menu", required: false)
    </div>
    <div class="content-main">
        @RenderBody()
    </div>
</div>

@section scripts
{
    @RenderSection("scripts", required: false)
}